/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TimeTableUI;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Harith
 */
public class visitingLecturerReportgen extends javax.swing.JFrame {

    /**
     * Creates new form visitingLecturerReportgen
     */
    public visitingLecturerReportgen() {
        initComponents();
           setIconImage();
        
    }
    
       private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("timetable_60px.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Home = new javax.swing.JButton();
        View1 = new javax.swing.JButton();
        Add1 = new javax.swing.JButton();
        Edit1 = new javax.swing.JButton();
        Print = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TEMPORERY ID", "NAME", "EMAIL", "CONTACT NUMBER", "SUBJECT VENUE"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 190, 750, 350));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("           VIEW");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(738, 606, 170, 50));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/print.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 560, 100, 100));

        Home.setBackground(new java.awt.Color(215, 82, 16));
        Home.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        Home.setForeground(new java.awt.Color(255, 255, 255));
        Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/home.png"))); // NOI18N
        Home.setText("HOME");
        Home.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Home.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Home.setIconTextGap(-20);
        Home.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Home.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        jPanel1.add(Home, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 17, 430, 120));

        View1.setBackground(new java.awt.Color(0, 0, 12));
        View1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        View1.setForeground(new java.awt.Color(255, 255, 255));
        View1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/view_1.png"))); // NOI18N
        View1.setText("VIEW LECTURER");
        View1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        View1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        View1.setIconTextGap(-20);
        View1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        View1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        View1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                View1MouseClicked(evt);
            }
        });
        jPanel1.add(View1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 410, 120));

        Add1.setBackground(new java.awt.Color(0, 0, 12));
        Add1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        Add1.setForeground(new java.awt.Color(255, 255, 255));
        Add1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/add.png"))); // NOI18N
        Add1.setText("ADD LECTURER");
        Add1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Add1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Add1.setIconTextGap(-20);
        Add1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Add1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Add1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Add1MouseClicked(evt);
            }
        });
        jPanel1.add(Add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 410, 120));

        Edit1.setBackground(new java.awt.Color(0, 0, 12));
        Edit1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        Edit1.setForeground(new java.awt.Color(255, 255, 255));
        Edit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        Edit1.setText("EDIT LECTURER");
        Edit1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Edit1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Edit1.setIconTextGap(-20);
        Edit1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Edit1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Edit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Edit1MouseClicked(evt);
            }
        });
        jPanel1.add(Edit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 410, 120));

        Print.setBackground(new java.awt.Color(0, 0, 12));
        Print.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        Print.setForeground(new java.awt.Color(255, 255, 255));
        Print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/print.png"))); // NOI18N
        Print.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Print.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Print.setIconTextGap(-20);
        Print.setLabel(" REPORT GENARATION");
        Print.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Print.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PrintMouseClicked(evt);
            }
        });
        Print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintActionPerformed(evt);
            }
        });
        jPanel1.add(Print, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 410, 120));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/visiting lecturer management rg.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 700));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/visiting lecturer management VIEW.jpg"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 700));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/print.png"))); // NOI18N
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 560, 100, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        // TODO add your handling code here:

        Home h = new Home();

        h.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_HomeMouseClicked

    private void View1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_View1MouseClicked
        // TODO add your handling code here:

        visitingLecturer v = new visitingLecturer();
        v.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_View1MouseClicked

    private void Add1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Add1MouseClicked
        // TODO add your handling code here:

        visitingLecturerAdd v = new visitingLecturerAdd();
        v.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_Add1MouseClicked

    private void Edit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Edit1MouseClicked
        // TODO add your handling code here:

        visitingLecturerEditUI v = new visitingLecturerEditUI();
        v.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_Edit1MouseClicked

    private void PrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PrintMouseClicked
        // TODO add your handling code here:

        visitingLecturerReportgen v = new visitingLecturerReportgen();
        v.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_PrintMouseClicked

    private void PrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrintActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(visitingLecturerReportgen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(visitingLecturerReportgen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(visitingLecturerReportgen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(visitingLecturerReportgen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new visitingLecturerReportgen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add1;
    private javax.swing.JButton Edit1;
    private javax.swing.JButton Home;
    private javax.swing.JButton Print;
    private javax.swing.JButton View1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
